import { Platform, StyleSheet } from "react-native";
import type { ThemeColors } from "../../theme/theme";

/** ========== Design tokens & styles ========== */
const SHADOW = Platform.select({
  ios: { shadowColor: "#000", shadowOpacity: 0.25, shadowRadius: 10, shadowOffset: { width: 0, height: 6 } },
  android: { elevation: 6 },
  default: {},
});

export const createAuthenticatedAppStyles = (colors: ThemeColors) => StyleSheet.create({
  appShell: { flex: 1 },
  loadingRoot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  loadingCard: {
    width: "100%",
    maxWidth: 360,
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
    gap: 12,
  },
  loadingTitle: { fontSize: 18, fontWeight: "800", textAlign: "center" },
  loadingSubtitle: { fontSize: 14, fontWeight: "600", textAlign: "center" },
  mainArea: { flex: 1 },

  defaultScreen: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, gap: 16 },
  defaultTitle: { color: colors.text, fontSize: 24, fontWeight: "800", textAlign: "center", letterSpacing: 0.3 },
  defaultSubtitle: { color: colors.subtext, fontSize: 14, textAlign: "center", lineHeight: 20, maxWidth: 320 },
  defaultCta: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 999,
    backgroundColor: colors.accent,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  defaultCtaText: { color: colors.accentFgOn, fontWeight: "800", fontSize: 14 },

  header: {
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.sidebarBg,
  },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12 },
  title: { color: colors.text, fontSize: 22, fontWeight: "800", letterSpacing: 0.3 },
  badge: { flexDirection: "row", alignItems: "center", gap: 6, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 999, backgroundColor: colors.surface },
  badgeText: { color: colors.subtext, fontSize: 12, fontWeight: "600" },

  chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 12 },
  filterChipsRow: { flexDirection: "row", gap: 8, flexWrap: "wrap", marginTop: 8 },
  chip: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 999, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, ...(SHADOW as object) },
  chipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipText: { color: colors.subtext, fontWeight: "700" },
  chipTextActive: { color: colors.accentFgOn, fontWeight: "800" },

  container: { padding: 16, gap: 14 },
  containerCompact: { paddingHorizontal: 12, paddingVertical: 16, gap: 16 },
  sectionLabel: { color: colors.text, fontSize: 14, fontWeight: "700", letterSpacing: 0.3, marginTop: 8 },
  filterLabel: { color: colors.subtext, fontSize: 12, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.4 },

  card: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 12, ...(SHADOW as object) },
  languageControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  languageLabel: { fontSize: 12, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.6 },
  languageOptions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  languageOption: {
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  languageOptionText: { fontWeight: "700", fontSize: 12 },
  statusHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  statusRefresh: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusRefreshText: { fontWeight: "700", fontSize: 12 },
  statusLoadingRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  statusErrorText: { fontSize: 12, fontWeight: "600" },
  statusList: { gap: 12 },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  statusLabelGroup: { flex: 1, gap: 2 },
  statusLabel: { fontSize: 13, fontWeight: "800" },
  statusDescription: { fontSize: 12, fontWeight: "600" },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusPillAvailable: {
    backgroundColor: applyAlpha(colors.accent, 0.15),
    borderColor: applyAlpha(colors.accent, 0.4),
  },
  statusPillUnavailable: {
    backgroundColor: applyAlpha(colors.danger, 0.12),
    borderColor: applyAlpha(colors.danger, 0.35),
  },
  statusPillUnauthorized: {
    backgroundColor: applyAlpha(colors.subtext, 0.12),
    borderColor: applyAlpha(colors.subtext, 0.3),
  },
  statusPillText: { fontWeight: "800", fontSize: 12 },
  input: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontWeight: "700",
    marginTop: 6,
  },
  filterRow: { flexDirection: "row", gap: 12, flexWrap: "wrap" },
  filterRowStack: { flexDirection: "column" },
  filterActions: { flexDirection: "row", justifyContent: "flex-end" },
  filterActionsCompact: { justifyContent: "flex-start" },
  listHeaderRow: { flexDirection: "row", alignItems: "center", gap: 12, justifyContent: "space-between" },
  listHeaderRowCompact: { flexDirection: "column", alignItems: "stretch", gap: 12 },
  listHeaderMeta: { alignItems: "flex-end", gap: 4 },
  listHeaderMetaCompact: { alignItems: "flex-start" },
  bookingListNotice: { color: colors.subtext, fontSize: 12, fontWeight: "600" },
  bookingListRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  bookingListRowCompact: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    alignSelf: "stretch",
  },
  bookingListSection: { gap: 12, marginTop: 18 },
  bookingListSectionFirst: { marginTop: 8 },
  bookingListSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bookingListSectionTitle: {
    color: colors.text,
    fontWeight: "800",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  bookingListSectionCount: { color: colors.subtext, fontWeight: "700", fontSize: 12 },
  bookingListTime: { width: 120, alignItems: "flex-start" },
  bookingListTimeCompact: { width: "100%" },
  bookingListClock: { color: colors.subtext, fontWeight: "700", fontSize: 12 },
  bookingListTitle: { color: colors.text, fontWeight: "800", fontSize: 15 },
  bookingListMeta: { color: colors.subtext, fontWeight: "600", fontSize: 12, marginTop: 2 },
  bookingStatusRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 },
  bookingStatusText: { fontSize: 12, fontWeight: "700" },
  bookingListActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  bookingListActionsCompact: {
    width: "100%",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },

  slotGroup: { gap: 8 },
  slotGroupTitle: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  slot: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 10, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface },
  slotPressed: { opacity: 0.7 },
  slotText: { color: colors.text, fontWeight: "700" },

  // seleção de horário
  slotActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  slotTextActive: { color: colors.accentFgOn },

  // slot ocupado
  slotBusy: { backgroundColor: "rgba(239,68,68,0.15)", borderColor: "rgba(239,68,68,0.4)" },
  slotBusyText: { color: colors.danger, textDecorationLine: "line-through", fontWeight: "700" },

  // slot indisponível (sem reserva direta)
  slotDisabled: { backgroundColor: applyAlpha(colors.subtext, 0.08), borderColor: applyAlpha(colors.subtext, 0.25) },
  slotDisabledText: { color: colors.subtext, fontWeight: "700", opacity: 0.7 },

  // resumo fixo
  summaryText: { marginTop: 10, textAlign: "center", color: colors.text, fontWeight: "700", fontSize: 14 },

  // botões
  bookBtn: { paddingVertical: 12, paddingHorizontal: 16, borderRadius: 12, backgroundColor: colors.accent, borderWidth: 1, borderColor: colors.accent },
  bookBtnDisabled: { opacity: 0.5 },
  bookBtnText: { color: colors.accentFgOn, fontWeight: "800" },

  empty: { color: colors.subtext, padding: 6 },

  bookingCard: {
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: applyAlpha(colors.accent, 0.2),
    backgroundColor: mixHexColor(colors.surface, colors.accent, 0.05),
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    ...(SHADOW as object),
  },
  bookingIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: applyAlpha(colors.accent, 0.12),
  },
  bookingContent: { flex: 1, gap: 8 },
  bookingHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 },
  bookingTitle: { color: colors.text, fontSize: 16, fontWeight: "800", flex: 1, flexWrap: "wrap" },
  bookingTimePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: applyAlpha(colors.accent, 0.12),
  },
  bookingTimeText: { color: colors.accent, fontSize: 12, fontWeight: "800", letterSpacing: 0.3 },
  bookingMetaRow: { flexDirection: "row", alignItems: "center", gap: 12, flexWrap: "wrap" },
  bookingMetaItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  bookingMetaText: { color: colors.subtext, fontSize: 13, fontWeight: "700" },
  cancelBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: applyAlpha(colors.danger, 0.45),
    backgroundColor: applyAlpha(colors.danger, 0.1),
  },
  cancelText: { color: colors.danger, fontWeight: "800", fontSize: 13 },

  note: { color: colors.subtext, fontSize: 12, marginTop: 8 },

  loadingOverlay: { position: "absolute", inset: 0, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.15)" },

  // Modal
  backdrop: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.45)", padding: 16 },
  sheet: {
    width: 560,
    maxWidth: "100%",
    maxHeight: "90%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.sidebarBg,
    padding: 16,
    gap: 12,
  },
  sheetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  sheetScroll: { alignSelf: "stretch", flexGrow: 1 },
  tab: { borderWidth: 1, borderColor: colors.border, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 999 },
  tabText: { color: colors.text, fontWeight: "800" },

  // linha lista
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderRadius: 14,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
  },
  cardRowStack: { flexDirection: "column", alignItems: "stretch", gap: 12 },
  smallBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  smallBtnDisabled: { opacity: 0.5 },
  stockModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "center",
    padding: 20,
  },
  stockModalCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 20,
    gap: 12,
  },
  stockModalTitle: { fontSize: 18, fontWeight: "800" },
  stockModalSubtitle: { fontSize: 13, fontWeight: "600" },
  stockModalLabel: { fontSize: 12, fontWeight: "700" },
  stockQuantityInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: "700",
    backgroundColor: "rgba(15,23,42,0.35)",
  },
  stockModalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  adjustmentModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "center",
    padding: 20,
  },
  adjustmentModalCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 20,
    gap: 14,
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
  },
  adjustmentModalTitle: { fontSize: 18, fontWeight: "800" },
  adjustmentModalSubtitle: { fontSize: 13, fontWeight: "600" },
  adjustmentModalLabel: { fontSize: 12, fontWeight: "700" },
  adjustmentTextInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: "700",
    backgroundColor: "rgba(15,23,42,0.35)",
  },
  adjustmentTextArea: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: "600",
    minHeight: 96,
    backgroundColor: "rgba(15,23,42,0.35)",
  },
  adjustmentHelperText: { fontSize: 12, fontWeight: "600" },
  adjustmentErrorText: { fontSize: 12, fontWeight: "700" },
  adjustmentModalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  fullWidthButton: {
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  cashHeaderActions: { flexDirection: "row", alignItems: "center", gap: 10 },
  cashHeaderActionsCompact: { flexDirection: "column", alignItems: "stretch", gap: 10, width: "100%" },
  secondaryCta: {
    marginTop: 0,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: applyAlpha(colors.accent, 0.12),
  },
  secondaryCtaText: { color: colors.accent, fontWeight: "800", fontSize: 14 },
  whatsappBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
  confirmBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
  serviceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  packageRow: {
    alignItems: "flex-start",
  },
  packageBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  packageItemsList: {
    gap: 4,
  },
  packageItemsLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  packageItemText: {
    fontSize: 12,
    fontWeight: "600",
  },
  serviceActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  productCard: {
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    backgroundColor: colors.surface,
    gap: 12,
  },
  productCardCompact: {
    padding: 14,
  },
  productHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  productName: {
    fontSize: 16,
    fontWeight: "800",
    flexShrink: 1,
  },
  productChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productChip: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 2,
  },
  productChipLabel: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  productChipValue: {
    fontSize: 14,
    fontWeight: "700",
  },
  productSkuChip: {
    alignSelf: "flex-start",
    backgroundColor: applyAlpha(colors.border, 0.2),
  },
  productDescriptionBlock: {
    gap: 4,
  },
  productDescription: {
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 17,
  },
  productActionsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "stretch",
  },
  productActionsContainerStacked: {
    flexDirection: "column",
  },
  productActionButton: {
    flexGrow: 1,
    minWidth: 140,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  productActionButtonFullWidth: {
    width: "100%",
  },
  productPrimaryAction: {
    borderColor: colors.accent,
    backgroundColor: applyAlpha(colors.accent, 0.12),
  },
  productSecondaryAction: {
    borderColor: colors.border,
    backgroundColor: applyAlpha(colors.border, 0.12),
  },
  productDangerAction: {
    borderColor: colors.danger,
    backgroundColor: applyAlpha(colors.danger, 0.12),
  },
  productActionLabel: {
    fontSize: 14,
    fontWeight: "800",
  },
  productActionPrimaryLabel: {
    color: colors.accent,
  },
  productActionSecondaryLabel: {
    color: colors.subtext,
  },
  productActionDangerLabel: {
    color: colors.danger,
  },
  productActionDisabled: {
    opacity: 0.55,
  },
  productActionDisabledLabel: {
    color: colors.subtext,
  },
  cashSummaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  cashSummaryItem: {
    flex: 1,
    minWidth: 160,
    padding: 14,
    borderWidth: 1,
    borderRadius: 14,
    borderColor: colors.border,
    backgroundColor: mixHexColor(colors.surface, colors.accent, 0.04),
    gap: 6,
  },
  cashSummaryLabel: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  cashSummaryValue: { fontSize: 20, fontWeight: "800", color: colors.text },
  cashAmount: { fontSize: 16, fontWeight: "800" },
  cashAmountPositive: { color: colors.accent },
  cashAmountNegative: { color: colors.danger },
  cashEntryRow: {
    gap: 10,
    padding: 14,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: colors.border,
    backgroundColor: mixHexColor(colors.surface, colors.accent, 0.03),
  },
  cashEntryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  cashEntryInfo: { flex: 1, gap: 4 },
  cashEntryType: {
    color: colors.subtext,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  cashEntrySource: { color: colors.text, fontSize: 15, fontWeight: "800" },
  cashEntryMetaRow: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  cashEntryMeta: { color: colors.subtext, fontSize: 12, fontWeight: "600" },
  cashEntryNote: { color: colors.subtext, fontSize: 12, fontStyle: "italic" },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statsGridCompact: { gap: 10, justifyContent: "space-between" },
  statCard: {
    flex: 1,
    minWidth: 180,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    gap: 12,
  },
  statCardCompact: {
    flexGrow: 0,
    flexBasis: "48%",
    minWidth: "48%",
    padding: 12,
    borderRadius: 14,
    gap: 8,
  },
  statCardHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  statIconBubble: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  statIconBubbleCompact: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  statLabel: { fontSize: 12, fontWeight: "700", textTransform: "uppercase" },
  statLabelCompact: { fontSize: 11 },
  statValue: { fontSize: 24, fontWeight: "800" },
  statValueCompact: { fontSize: 20 },
  statDetail: { fontSize: 12, fontWeight: "600" },
  statDetailCompact: { fontSize: 11 },
  statChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  statProgressTrack: {
    height: 6,
    borderRadius: 999,
    overflow: "hidden",
  },
  statProgressTrackCompact: {
    height: 5,
  },
  statProgressFill: { height: "100%", borderRadius: 999 },
  insightsRow: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  insightSection: {
    flex: 1,
    minWidth: 220,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    gap: 12,
  },
  insightSectionHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  insightSectionTitle: { fontSize: 14, fontWeight: "800" },
  insightSectionSubtitle: { fontSize: 12, fontWeight: "600" },
  pieChartBlock: { flexDirection: "row", alignItems: "center", gap: 16 },
  pieChartBlockCompact: { flexDirection: "column" },
  pieChartWrapper: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
  },
  pieChartCenter: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    gap: 2,
    zIndex: 2,
  },
  pieChartValue: { fontSize: 20, fontWeight: "800" },
  pieChartLabel: { fontSize: 12, fontWeight: "700" },
  pieLegend: { flex: 1, gap: 10 },
  pieLegendTitle: { fontSize: 11, fontWeight: "700", textTransform: "uppercase" },
  pieLegendItem: { flexDirection: "row", alignItems: "center", gap: 10 },
  pieLegendSwatch: { width: 12, height: 12, borderRadius: 6 },
  pieLegendLabel: { fontSize: 13, fontWeight: "700" },
  pieLegendMeta: { fontSize: 12, fontWeight: "600" },
  highlightGroup: { gap: 8 },
  highlightPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  chartCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 16,
  },
  barChart: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 4,
  },
  barColumn: { flex: 1, minWidth: 36, alignItems: "center", gap: 8 },
  barValue: { fontSize: 13, fontWeight: "700" },
  productBarUnits: { fontSize: 13, fontWeight: "700", textAlign: "center" },
  barTrack: {
    width: 28,
    height: 120,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  barFill: { width: "100%", borderRadius: 14 },
  barLabel: { fontSize: 11, fontWeight: "700", textTransform: "uppercase" },
  productBarPrice: { fontSize: 11, fontWeight: "600", textAlign: "center" },
  productBarName: { fontSize: 12, fontWeight: "700", textAlign: "center" },
  leaderboard: { gap: 12 },
  leaderboardRow: { gap: 8, paddingVertical: 4 },
  leaderboardInfo: { flexDirection: "row", alignItems: "center", gap: 8 },
  leaderboardBarTrack: { width: "100%", height: 6, borderRadius: 999, overflow: "hidden" },
  leaderboardBarFill: { height: "100%", borderRadius: 999 },
  teamList: { borderWidth: 1, borderRadius: 12, padding: 12, gap: 12 },
  teamListRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  teamListIcon: { marginTop: 2 },
  teamListInfo: { flex: 1, gap: 6 },
  teamRoleBadge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2 },
});

export type AuthenticatedAppStyles = ReturnType<typeof createAuthenticatedAppStyles>;
